version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      electron:
        patterns: ['electron', 'electron-*', '@electron/*']
      development-tooling:
        dependency-type: development
        exclude-patterns: ['electron', 'electron-*', '@electron/*']
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
